import { ThemeProvider } from "@/components/themeProvider";
import type { Theme } from "@/components/themeProvider";

import "@/styles/globals.css";
import { getCookie } from "@/util/helpers/getCookie";

import { GeistSans } from "geist/font/sans";

export const metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }]
};

export default async function RootLayout({
    children
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${GeistSans.className} bg-white dark:bg-black`}>
                <ThemeProvider
                    cookie={await getCookie<Theme>("theme", "system")}
                >
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
