import { ThemeProvider, getServerTheme } from "next-server-theme/server";

import { GeistSans } from "geist/font/sans";

import "./globals.css";

export const metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }]
};

export default function RootLayout({
    children
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body
                className={`${GeistSans.className} pink:bg-pink-100 flex h-screen w-screen items-center justify-center bg-white dark:bg-black`}
            >
                {children}
            </body>
        </html>
    );
}
