import { ThemeProvider } from "@/components/themeProvider";
import { getServerTheme } from "@/util/helpers/getServerTheme";

import "./globals.css";

import { GeistSans } from "geist/font/sans";

export const metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }]
};

export default async function RootLayout({
    children
}: {
    children: React.ReactNode;
}) {
    return (
        <html
            lang="en"
            suppressHydrationWarning
            className={await getServerTheme()}
        >
            <body className={`${GeistSans.className} bg-white dark:bg-black`}>
                <ThemeProvider>{children}</ThemeProvider>
            </body>
        </html>
    );
}
