import { ThemeProvider } from "@/components/themeProvider";
import { getServerTheme } from "@/util/getServerTheme";

import "./globals.css";

import { GeistSans } from "geist/font/sans";

export const metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }]
};
import { cosmiconfig } from "cosmiconfig";
//import { cosmiconfigSync, cosmiconfig } from "cosmiconfig";
//import { lilconfig, lilconfigSync } from "lilconfig";

if (typeof window === "undefined") {
    // try {
    //     const explorerSync = cosmiconfigSync("myapp");
    //     console.log(explorerSync);
    //     const result = explorerSync.search();
    //     console.log(result);
    // } catch (e) {
    //     console.error(e);
    // }
    (async () => {
        try {
            const config = await import("theme.config.js");
            console.log(config.default);
            const explorerSync = await cosmiconfig("theme");
            const result = await explorerSync.search();
            console.log(result);
            // const result = await lilconfig("theme").search();
            // console.log(result);
        } catch (e) {
            //console.error(e);
        }
    })();
}

export default function RootLayout({
    children
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" suppressHydrationWarning className={getServerTheme()}>
            <body
                className={`${GeistSans.className} bg-white dark:bg-black pink:bg-pink-100`}
            >
                <ThemeProvider>{children}</ThemeProvider>
            </body>
        </html>
    );
}
