import { ThemeProvider } from "@/components/themeProvider";
import { getServerTheme } from "@/util/getServerTheme";

import "./globals.css";

import { GeistSans } from "geist/font/sans";

export const metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }]
};

export default function RootLayout({
    children
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body
                className={`${GeistSans.className} bg-white dark:bg-black pink:bg-pink-100`}
            >
                <ThemeProvider
                    defaultTheme="pink"
                    systemLightTheme="pink"
                    systemDarkTheme="light"
                >
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
